// js/data.js
// Konvertiere Datum-Strings in Date-Objekte und exportiere die Daten
export const breakthroughData = [
    // Bestehende Daten
    { id: 3, group: 'ai', content: 'Deep Blue besiegt Kasparov', start: '1997-05-11', details: 'Der IBM-Supercomputer Deep Blue besiegt den amtierenden Schachweltmeister Garri Kasparov in einem Match.' },
    { id: 15, group: 'science', content: 'Graphen isoliert', start: '2004-10-22', details: 'Andre Geim und Konstantin Novoselov isolieren erstmals Graphen, ein zweidimensionales Material mit außergewöhnlichen Eigenschaften, was ihnen den Nobelpreis einbringt.' },
    { id: 11, group: 'ai', content: 'Deep Belief Nets', start: '2006-10-01', details: 'Geoffrey Hinton et al. veröffentlichen einen schnellen Lernalgorithmus für Deep Belief Nets, was das Interesse an Deep Learning neu entfacht.' },
    { id: 16, group: 'science', content: 'Erste synthetische Zelle', start: '2010-05-20', details: 'Das J. Craig Venter Institute erschafft die erste synthetische, sich selbst replizierende Bakterienzelle und legt damit einen Grundstein der synthetischen Biologie.' },
    { id: 12, group: 'ai', content: 'Watson gewinnt Jeopardy!', start: '2011-02-16', details: 'IBMs KI-System Watson besiegt die besten menschlichen Spieler in der Quizshow Jeopardy! und demonstriert Fortschritte im Verstehen natürlicher Sprache.' },
    { id: 25, group: 'science', content: 'Curiosity landet auf dem Mars', start: '2012-08-06', details: 'NASAs Rover Curiosity landet erfolgreich auf dem Mars, um nach Spuren von vergangenem Leben zu suchen und die geologische Geschichte des Planeten zu untersuchen.' },
    { id: 17, group: 'science', content: 'Higgs-Boson entdeckt', start: '2012-07-04', details: 'Das CERN gibt die Entdeckung eines neuen Teilchens bekannt, das mit dem Higgs-Boson konsistent ist, einem entscheidenden Baustein des Standardmodells der Teilchenphysik.' },
    { id: 6, group: 'science', content: 'CRISPR-Cas9 als Gen-Werkzeug', start: '2012-06-28', details: 'Charpentier und Doudna veröffentlichen ihre Entdeckung, wie CRISPR-Cas9 zur gezielten Genom-Editierung verwendet werden kann. KI-Modelle helfen heute bei der Optimierung von CRISPR-Anwendungen.' },
    { id: 4, group: 'science', content: 'Menschliches Genom sequenziert', start: '2003-04-14', details: 'Das Human Genome Project schließt die Sequenzierung des menschlichen Genoms ab, ein Meilenstein für die Medizin.' },
    { id: 5, group: 'ai', content: 'AlexNet gewinnt ImageNet', start: '2012-09-30', details: 'Ein neuronales Netz namens AlexNet gewinnt den ImageNet-Wettbewerb mit einer signifikant niedrigeren Fehlerrate und löst die Deep-Learning-Revolution aus.' },
    { id: 13, group: 'ai', content: 'GANs', start: '2014-06-10', details: 'Ian Goodfellow stellt Generative Adversarial Networks (GANs) vor, die es KIs ermöglichen, realistische Bilder, Töne und Texte zu erzeugen.' },
    { id: 18, group: 'science', content: 'Gravitationswellen nachgewiesen', start: '2016-02-11', details: 'Das LIGO-Observatorium gibt den ersten direkten Nachweis von Gravitationswellen bekannt, die von zwei kollidierenden Schwarzen Löchern erzeugt wurden und Einsteins Vorhersage bestätigen.' },
    { id: 7, group: 'ai', content: 'AlphaGo besiegt Lee Sedol', start: '2016-03-15', details: 'Googles AlphaGo besiegt den Weltmeister Lee Sedol im Go, einem Spiel, das als weitaus komplexer als Schach gilt.' },
    { id: 14, group: 'ai', content: 'Transformer-Architektur', start: '2017-06-12', details: 'Die Google-Veröffentlichung "Attention Is All You Need" stellt die Transformer-Architektur vor, die zur Grundlage moderner Sprachmodelle wie GPT wird.' },
    { id: 19, group: 'ai', content: 'BERT', start: '2018-10-11', details: 'Google veröffentlicht BERT, ein Sprachmodell, das durch das beidseitige Betrachten von Textkontexten neue Maßstäbe im Sprachverständnis setzt.' },
    { id: 8, group: 'science', content: 'Erstes Bild eines Schwarzen Lochs', start: '2019-04-10', details: 'Das Event Horizon Telescope-Projekt veröffentlicht das erste direkte Bild eines Schwarzen Lochs. KI-Algorithmen waren entscheidend, um die Daten von Teleskopen weltweit zu einem Bild zusammenzufügen.' },
    { id: 20, group: 'science', content: 'AlphaFold 2 löst Proteinfaltung', start: '2020-11-30', details: 'DeepMinds KI AlphaFold 2 löst das 50 Jahre alte Problem der Proteinfaltung mit hoher Genauigkeit, ein Durchbruch für die Biologie und Medizin.' },
    { id: 9, group: 'ai', content: 'Veröffentlichung von GPT-3', start: '2020-06-11', details: 'OpenAI veröffentlicht GPT-3, eines der bis dahin größten und fähigsten Sprachmodelle, das die Tür für eine neue Generation von KI-Anwendungen öffnet.' },
    { id: 21, group: 'ai', content: 'DALL-E', start: '2021-01-05', details: 'OpenAI stellt DALL-E vor, ein neuronales Netz, das aus Textbeschreibungen Bilder erzeugt und damit die kreativen Fähigkeiten von KI demonstriert.' },
    { id: 22, group: 'ai', content: 'GitHub Copilot', start: '2021-06-29', details: 'GitHub und OpenAI starten GitHub Copilot, einen KI-gestützten Programmierassistenten, der Code direkt im Editor vorschlägt.' },
    { id: 23, group: 'science', content: 'James Webb Teleskop startet', start: '2021-12-25', details: 'Das James Webb Space Telescope, das leistungsstärkste je gebaute Weltraumteleskop, startet seine Mission, um die Frühzeit des Universums zu erforschen.' },
    { id: 24, group: 'ai', content: 'Stable Diffusion', start: '2022-08-22', details: 'Die Veröffentlichung des Open-Source-Modells Stable Diffusion macht hochwertige Text-zu-Bild-Generierung für eine breite Öffentlichkeit zugänglich.' },
    { id: 10, group: 'ai', content: 'Veröffentlichung von ChatGPT', start: '2022-11-30', details: 'OpenAI veröffentlicht ChatGPT, ein Modell, das die öffentliche Wahrnehmung von KI nachhaltig verändert und einen globalen Hype auslöst.' },
].map(d => ({ ...d, date: new Date(d.start) }));